### ISSUE TITLE
non-existent field 'globalIDs'

### ISSUE THREAD

**Issue by omidm7** [bahanonu/calciumImagingAnalysis#21]
Hey Biafra!
I am running computeMatchObjectsbtwSessions on a new data set and encountering that error that you previously fixed, something about dividing by zeros after CNMF-e? 

![image](https://user-images.githubusercontent.com/44180252/58765234-88fbd380-8525-11e9-9052-aa3b9d99111d.png)

Omid

**Comment by bahanonu** [comment]
Hey Omid,

Could you let me know the inputs you used to run `computeMatchObjBtwnTrials` method?

cheers!
-Biafra

**Comment by omidm7** [comment]
Sure! I'm using the following settings:
# of rounds to register: 1
distance to match: 7
image threshold: 0.4
session to align to: blank
2 = no iso scaling

**Comment by omidm7** [comment]
I also uploaded the file folders for all 4 sessions onto box, in case you want the data. 
Omid

**Comment by bahanonu** [comment]
Thanks, ran in through the master and most recent branch without any new commits (see https://github.com/bahanonu/calciumImagingAnalysis/tree/bahanonu/functionUpdates) and runs fine. What Matlab version are you running? If you run with the most recent master or `functionUpdates` branch, what happens?

Also, looking at the size of the movies and since they appear to be different trials of the same overall imaging session, might be beneficial to run all the movies through a common processing if on the same day then computationally separate out the data downstream, that's what I did for the _Science_ paper.

![m01_matchedCells](https://user-images.githubusercontent.com/5241605/58827779-b5cceb00-85f8-11e9-9f17-dea2e5428984.gif)

**Comment by omidm7** [comment]
Yeah I've tried running from the master and functionupdates, still getting the same error. I'm using Matlab2017b.
I just tried running matchobjbtwsessions on 5 sessions from a previous data set, and it works just fine! Very bizarre.

**Comment by omidm7** [comment]
Ok, after re-running cnmf-e on the same data, it's working now.  🤷🏻‍♂️

**Comment by bahanonu** [comment]
Next time the error occurs, can you save your workspace as a MAT-file so I can a look directly at that run in the appropriate MATLAB version? 

Also, `2019_06_01_p001_m01_homecage01_trial01` does not appear to have finished manually sorting, when you got the previous error was that after manually sorting?

**Comment by omidm7** [comment]
Yup, I had sorted. That might have been the problem?
I just sorted again, ran the cross session alignment, and everything seems to be fine. Thanks a lot!

If you've ever got time on your hands, I have never been able to get the modelModifymovies to work correctly. The imageJ prompts guide me to crop a region, then hit yes to move on to the next movie. When I do this, I get a prompt that says "unrecognized command: close all without saving" or something. 
It's nothing urgent, since I can manually crop the videos before processing, but it would be awesome if I could just insert 'NaN's for unnecessary regions. 
Cheers,
Omid

**Comment by bahanonu** [comment]
Good to hear it worked out. And yep, imagine that might have been it, I might add a check to the signalSorter to verify with the user that they have done all the sorting, since have seen other users where sorting wasn't entirely complete and issues appeared later.  

I've planned to add a version that uses Matlab figures instead for cases in which Miji isn't working on a machine (as is the case for other parts of the pipeline). Will put in a pull request when that's up.
