### ISSUE TITLE
Trouble loading demo data

### ISSUE THREAD

**Issue by omidm7** [bahanonu/calciumImagingAnalysis#8]
Hi Biafra,
I'm running MATLAB_2017b on Mac OS. I know you haven't tested on either of these, but I'm hoping there might be an easy solution.

I have downloaded the demo data to the path:
/omidd/calciumImagingAnalysis/data/2014_04_01_p203_m19_check01_raw, and typed that exact pathname in the window that opens up after you click ModelAddNewFolders. 

When I then try to view the movie through the viewMovie module, a series of prompts (animal number, session number, etc) leads me to an open Finder window where I'm asked to open a file. I'm not sure what I'm supposed to open in this window. Is it the movie file? Unfortunately that seems to be greyed out. Does this mean I have not loaded the files correctly?

The error code I ultimately get is:
![image](https://user-images.githubusercontent.com/44180252/51719440-55042500-1ffe-11e9-8489-92f9623ef132.png)

Miji has been set up correctly, because I can use the command MIJ.start.

Omid

**Comment by bahanonu** [comment]
Hey Omid,

I'm assuming you haven't run preprocessing? If not, then the class may be searching for the wrong file (e.g. one that contains `crop` in the pathname instead of the raw movies `concat`). If you want to look at the raw movie, change the `Image movie regexp` in the `viewMovie` settings that pop-up:

![image](https://user-images.githubusercontent.com/5241605/51725501-63ab0600-2017-11e9-94e3-182fcd55fa22.png)

As a heads up, in the https://github.com/bahanonu/calciumImagingAnalysis#processing-calcium-imaging-data section I note:
- `viewMovie`
  - Users should check that calciumImagingAnalysis loads their movies correctly and that Miji is working.
  - Remember to check that Imaging movie regexp: (regular expression class uses to find user movies within given folders) setting matches name of movies currently in repository.

Thanks for the heads up, I'll make a slight fix to the code so this confusion doesn't happen for other new users.

cheers,
-Biafra

**Comment by omidm7** [comment]
Hi Biafra,
Correct, I was just trying to make sure I could open the movie before preprocessing. I changed the regexp field to concat, but still get the following error: 
![image](https://user-images.githubusercontent.com/44180252/51769742-a06b1180-2098-11e9-8a3b-d98039e9050c.png)

I'm starting to think I am not using the ModelAddNewFolders step correctly. Can you take a look at how I've written the folder path:
![image](https://user-images.githubusercontent.com/44180252/51769870-fb9d0400-2098-11e9-8898-b7338975e300.png)

Finally, after the last ViewMovie prompt (movie titles, labels and such), this Finder window opens. What am I supposed to open here? You'll notice the demo data is greyed out. I have tried uploading my own data sets but encounter the same problem.
![image](https://user-images.githubusercontent.com/44180252/51770044-8a118580-2099-11e9-9f64-78a39a002d8b.png)

Omid

**Comment by bahanonu** [comment]
@omidm7 
Enter the path name without the single quotations marks and let me know if it works.

(MATLAB is considering those as part of the path hence isn't technically looking in the correct directory and I avoid stripping characters from the path users enter in case that is in the folder name for specific reasons.)

To be clear, is that opening before or after the below?
![image](https://user-images.githubusercontent.com/5241605/51770544-03f63e80-209b-11e9-9a38-0f6709cf9c72.png)

**Comment by omidm7** [comment]
@bahanonu, I have tried removing the single quotation marks and it still can't load the folder correctly.
The first error message I see is:
![image](https://user-images.githubusercontent.com/44180252/51854234-2d9fa780-22df-11e9-8af4-6382ee84d8b7.png)

And then after going through the video settings prompts, I see:

![image](https://user-images.githubusercontent.com/44180252/51854289-5031c080-22df-11e9-8d09-c3ec284e38eb.png)

I can pull up Fiji by running the command MIJ.start.

**Comment by bahanonu** [comment]
@omidm7 

The first is just a message letting the user know that the default regexp (crop) does not yield files, so class is falling onto the first backup regexp (concat). That warning message can be ignored since built-in Matlab functions give that to warn of changes to new releases (you'll see it often re: `DrawMode` property in different contexts).

Strange still not finding `concat_recording_20140401_180333.h5` file, if you type the below into Matlab (with PATH replaced with the path where `concat_recording_20140401_180333.h5` is located), what output do you see?
```Matlab
cellfun(@disp,getFileList('PATH','concat'));
```

re: Miji,
If you type 
```Matlab
Miji;
```
into Matlab command window, what happens? The `Java exception occured:` error message occurs if Miji did not initialize Fiji properly, e.g. before that message, does Fiji initialize?.

**Comment by bahanonu** [comment]
@omidm7 

Just tested a fresh master repository branch with 2017b on OSX 10.10.5 and able to open up/view the raw file `concat_recording_20140401_180333.h5` fine in Fiji. 

Can you type the below into Matlab and send a screenshot of the output? Wondering if there is still some error with how the folder was entered into the class.
```Matlab
obj.inputFolders
```

**Comment by omidm7** [comment]
@bahanonu 
Ok. I just installed the version of ImageJ you recommended earlier, and followed the instructions for adding the miji. Here is the screenshot of the error. 

![image](https://user-images.githubusercontent.com/44180252/51862171-df949f00-22f2-11e9-9c45-c9fc52e70f42.png)

However, when I type MIJ.start, Fiji opens up.
![image](https://user-images.githubusercontent.com/44180252/51863177-2e433880-22f5-11e9-86f1-0e28952dde23.png)

Typing Miji; returns: Undefined function or variable.

Here are the other inputs you asked for:
![image](https://user-images.githubusercontent.com/44180252/51863294-7e21ff80-22f5-11e9-9b96-18a3e74dfb9c.png)

![image](https://user-images.githubusercontent.com/44180252/51863516-1324f880-22f6-11e9-890f-686ce2e392df.png)
(The cellfun function didn't return any lists.)

I really appreciate your help with this!

**Comment by bahanonu** [comment]
Yep! We'll get this resolved.

Looks like the paths aren't correct. Can you send output of the below (basing off of the path on your Matlab screenshot). Note that the __/__ backslash needs to be in front of Users else OSX won't consider it valid.
```Matlab
cellfun(@disp,getFileList('/Users/omidd/calciumImagingAnalysis/data/2014_04_01_p203_m19_check01_raw','concat'));
```

 `obj.inputFolders` should point to `/Users/omidd/calciumImagingAnalysis/data/2014_04_01_p203_m19_check01_raw` rather than `/calciumImagingAnalysis/data/2014_04_01_p203_m19_check01_raw`. Can you enter the former in as the path in `modelAddNewFolders` module and let me know if that resolves the issue?

re: Miji, interesting wonder why it started fine on my OSX Matlab, can you send me the output of the below line of code in Matlab. Else I'll update so that if `Miji` doesn't work, it'll fallback on `MIJ.start`.

```Matlab
pathCell = regexp(path, pathsep, 'split'); idx = find(~cellfun(@isempty,regexpi(pathCell,'Fiji'))); display(idx); pathCell(idx)
```

**Comment by bahanonu** [comment]
Also, if you are using Github, pull the `bahanonu/functionUpdates` branch for now until we get this resolved, as has updates for this and other UI changes.
https://github.com/bahanonu/calciumImagingAnalysis/tree/bahanonu/functionUpdates

**Comment by omidm7** [comment]
Ok! Changing the path name to the full root name fixed the issue. I can access the file through obj.inputFolders. 

Here are the outputs of the two MIJI lines you asked for:
![image](https://user-images.githubusercontent.com/44180252/51866525-05737100-22fe-11e9-8a03-523222ce83fe.png)

**Comment by omidm7** [comment]
Also, I changed 'Miji' in line 149 of viewmovie to MIJ.start and it works now. :) 
Thanks so much! Marching on.

**Comment by bahanonu** [comment]
@omidm7 
Great! Let me know if you run into any other issues.

Wondering why you're able to start Miji without Fiji in the path. Do you see it when you click 'Set Path' in the toolbar?

**Comment by omidm7** [comment]
@bahanonu I think because I put:

javaaddpath '/Applications/MATLAB_R2017b.app/java/mij.jar'
javaaddpath '/Applications/MATLAB_R2017b.app/java/ij-1.52i.jar'

in startup.m?
